### ISSUE TITLE
web site

### ISSUE THREAD

**Issue by gigster99** [rhizomik/redefer-rdf2html#1]
Roberto, is your website offline?
http://rhizomik.net/html/redefer/rdf2html-form/

/jay gray

**Comment by rogargon** [comment]
This might have been a temporal connectivity issue, it seems to be working now.

Thank you

**Comment by gigster99** [comment]
Hmmm. I have this URL in my bookmarks:

http://rhizomik.net/html/redefer/rdf2html-form/

Two days ago the site was available to me. I just checked again and see this in Chrome:

![rhizomik_chrome_](https://cloud.githubusercontent.com/assets/2052894/15962294/a57f7a84-2ecf-11e6-81df-2c713a387ed8.png)

And see this in Firefox:

![rhizomik_firefox_](https://cloud.githubusercontent.com/assets/2052894/15962302/b8351ee0-2ecf-11e6-8009-4af337e301b0.png)

I do run a black-list for my browsers and I just checked to see if I had mistakenly added your domain, but no, as shown here:
![blacklist_](https://cloud.githubusercontent.com/assets/2052894/15962357/31a04b92-2ed0-11e6-80d9-1db35b024c63.png)

In fact you are in my white-list as shown here:
![whitelist_](https://cloud.githubusercontent.com/assets/2052894/15962408/7736f6b0-2ed0-11e6-92a4-dbd7b05e17ab.png)

Any idea what might be happening?

**Comment by rogargon** [comment]
It seems to be a problem with our domain name provider. We have contacted them and trying to solve it. Meanwhile, can you check with a different computer or restarting it? It is working for us most of the time and it seems related with DNS caching...

**Comment by gigster99** [comment]
Good that you can see the problem. We use your service extensively, but not urgently, so no problemo is this takes time to work out. ITMT, we'll try different computers and see if the problem is exclusively on our side.

**Comment by rogargon** [comment]
Solved. We have been told that the DNS has been refreshed and that it might take some hours to propagate globally. Thanks for your patience

**Comment by gigster99** [comment]
Sites are 'back to normal'.
